language: node_js
node_js:
  - 12.6.0

branches:
  except:
    - dev
    - /^dev-.+$/

before_install:
  - yarn global add lerna

install:
  - lerna bootstrap --force-local

script:
  - yarn run lint
