language: node_js
node_js:
  - 10.16.0
  - 12.13.0

branches:
  except:
    - dev
    - /^dev-.+$/
    - /^dependabot.+$/

before_install:
  - yarn global add lerna

install:
  - lerna bootstrap --force-local

script:
  - commitlint-travis
  - yarn run lint
